export enum OrderType {
  NONE = 'NONE',
  DEPOSIT_ESCROW = 'DEPOSIT_ESCROW',
  FULLY_DEPOSITED = 'FULLY_DEPOSITED',
  CANCLED = 'CANCLED',
  ON_WAITING_REFUND = 'ON_WAITING_REFUND',
  SELLER_FINALIZED = 'SELLER_FINALIZED',
  ORDER_RECEIVED = 'ORDER_RECEIVED',
  DONE = 'DONE',
}
